apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: job-board

resources:
- ../../base

images:
- name: backend-placeholder
  newName: 556789079263.dkr.ecr.eu-west-2.amazonaws.com/my-k8/backend
  newTag: e175783
- name: frontend-placeholder
  newName: 556789079263.dkr.ecr.eu-west-2.amazonaws.com/my-k8/frontend
  newTag: e175783

patches:
- path: replica-patch.yaml
- path: resource-patch.yaml
